project:
  type: book
  output-dir: ../docs
  execute-dir: project

book:
  title: "ESDC Roundtable Reports"
  author: "Thomas McManus"
  date: "2024-08-29"
  chapters:
    - index.qmd
    - planned-analysis.qmd
  favicon: assets/favicon.png
  sidebar:
    logo: assets/blueprint-logo.png

bibliography: references.bib

execute: 
  cache: true

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    code-fold: true
    code-summary: "Show code"



