project:
  type: book

book:
  title: "reports"
  author: "Norah Jones"
  date: "2024-08-29"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



