project:
  type: book
  output-dir: ../docs
  execute-dir: project

book:
  title: "reports"
  author: "Norah Jones"
  date: "2024-08-29"
  chapters:
    - index.qmd
    - planned-analysis.qmd
  favicon: assets/favicon.png
  sidebar:
    logo: assets/blueprint-logo.png

bibliography: references.bib

execute: 
  cache: true

format:
  html:
    theme: 
      - cosmo
      - custom.scss
  pdf:
    documentclass: scrreprt


